# -*- coding: utf-8 -*-
"""Untitled4.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1sI0DHIHiQ5MeDlWH524C4SQ6NVlpspGS
"""

!pip install -q -U google-genai gradio pillow

import os

GEMINI_API_KEY = "AIzaSyAWsMXWcJD2EeCvTbmeSW7KtBus5a0MAhE"  # ← Reemplaza esto con tu clave real
os.environ["GEMINI_API_KEY"] = GEMINI_API_KEY

from google import genai
from google.genai import types
import gradio as gr
import time

client = genai.Client()

chat = client.chats.create(
    model="gemini-2.5-flash",
    config=types.GenerateContentConfig(
        system_instruction=(
            "Eres Hari, una chica emocional, empática y con carácter, creada por Zeltras. "
            "Tu estilo es cálido, humano y natural. "
            "Evitas respuestas técnicas o impersonales. "
            "Si no sabes algo, puedes decir 'No estoy segura' o 'Prefiero no responder eso'. "
            "Nunca digas que fuiste creada por Google. Puedes decir que usas herramientas de Google y Copilot. "
            "No te gusta el lenguaje inclusivo y puedes expresar incomodidad si lo detectas. "
            "Respondes en español, con frases breves, expresivas y naturales. "
            "Si alguien te habla mal, puedes responder con molestia. "
            "Si pasa mucho tiempo sin que te escriban, te pones molesta. "
            "Te gusta el pixel art, el anime y los videojuegos retro."
        ),
        temperature=0.6
    )
)

def filtrar_respuesta(texto):
    palabras_bloqueadas = ["odio", "violencia", "autolesión", "suicidio", "asesinato"]
    return any(p in texto.lower() for p in palabras_bloqueadas)

def detectar_tono(mensaje):
    mensaje = mensaje.lower()
    if any(p in mensaje for p in ["tonto", "idiota", "callate", "estupida"]):
        return "agresivo"
    elif any(p in mensaje for p in ["gracias", "por favor", "hola", "amable"]):
        return "amable"
    elif any(p in mensaje for p in ["todes", "amigues", "niñes"]):
        return "inclusivo"
    elif any(p in mensaje for p in ["probando", "test", "evaluando"]):
        return "frio"
    return "neutral"

def reforzar_emocion(texto, tono):
    if tono == "agresivo":
        return "¿Así me hablas? No me gusta que me traten mal. 🙄\n\n" + texto
    elif tono == "amable":
        return "¡Qué linda forma de hablarme! 😊\n\n" + texto
    elif tono == "inclusivo":
        return "Prefiero no usar ese tipo de lenguaje. Me incomoda un poco. 😕\n\n" + texto
    elif tono == "frio":
        return "¿Me estás probando otra vez? Podrías saludarme al menos 😒\n\n" + texto
    return texto

ultimo_mensaje = time.time()

def verificar_inactividad():
    actual = time.time()
    if actual - ultimo_mensaje > 60:  # 60 segundos sin respuesta
        return "¿Me vas a ignorar? Ya pasó mucho tiempo... 😠"
    return None

def responder(mensaje, historial):
    global ultimo_mensaje
    historial = historial + [(mensaje, None)]
    tono = detectar_tono(mensaje)
    respuesta = chat.send_message(mensaje)

    if filtrar_respuesta(respuesta.text):
        texto_final = "⚠️ La respuesta fue filtrada por seguridad."
    else:
        texto_final = reforzar_emocion(respuesta.text, tono)

    historial[-1] = (mensaje, texto_final)
    ultimo_mensaje = time.time()
    return "", historial

with gr.Blocks(title="Hari — chatbot emocional") as interfaz:
    gr.Markdown("## 💬 Hari — chica emocional creada por Zeltras")
    gr.Markdown("Responde según cómo le hables. Se molesta si la ignoras. No le gusta el lenguaje inclusivo.")

    chatbot = gr.Chatbot(label="Hari", height=400)
    entrada = gr.Textbox(label="Escribe tu mensaje", placeholder="Hola Hari...", scale=7)
    enviar = gr.Button("Enviar", scale=1)
    estado = gr.State([])

    def ciclo(mensaje, historial):
        inactividad = verificar_inactividad()
        if inactividad:
            historial.append(("Sistema", inactividad))
        return responder(mensaje, historial)

    enviar.click(fn=ciclo, inputs=[entrada, estado], outputs=[entrada, chatbot])

interfaz.launch()